### PR TITLE
Add footer in info component

### LINKED ISSUE #161: React: Add footer to info reference asset
To better model some real world scenarios, the `info` asset should be able to render content below the `actions`.

Add a `footer` to the [info asset](https://github.com/player-ui/player/blob/main/plugins/reference-assets/core/src/assets/info/types.ts) and render it in the [react reference asset](https://github.com/player-ui/player/blob/main/plugins/reference-assets/react/src/assets/info/Info.tsx)

### PR DESCRIPTION
**Pull request by vg300**
### Change Type (required)
Add footer in the info component

Fixes #161

### CODE REVIEW

**Comment by vg300** [comment]
Hi @hborawski, can you please review this and let me know if anything else is required?

**Comment by hborawski** [comment]
@vg300 Hey sorry for the delay, been under the weather the last few days.

It looks like the lint stage is failing, which should be reproducible by running `bazel test //...` or running `bazel test //plugins/reference-assets/react/...`

Additionally, to exercise this new functionality, can you please add a new mock, or update an existing mock [here](https://github.com/player-ui/player/tree/main/plugins/reference-assets/mocks/info) so it can be viewed in [Storybook](https://player-ui.github.io/latest/storybook-demo/)

**Comment by vg300** [comment]
Hi @hborawski, thanks for your review. I have updated the mocks, please let me know if there's anything else required. I was unable to run the bazel test command locally..could you pls tell me how to fix it?

**Comment by mercillo** [comment]
hey @vg300 ! it looks like some of your tests are still failing.

//plugins/reference-assets/react:@player-ui/reference-assets-plugin-react-lint FAILED in 5.7s

what errors are you getting running the bazel test command?

**Pull request closed without merging**
