### PR TITLE
[Android] Fix stale state collection in from view model

### PR DESCRIPTION
**Pull request by sugarmanz**
### Change Type (required)
Indicate the type of change your pull request is:

- [x] `patch`
- [ ] `minor`
- [ ] `major`

### Does your PR have any documentation updates?
- [ ] Updated docs
- [x] No Update needed
- [ ] Unable to update docs

<details>
  <summary>📦 Published PR as canary version: <code>0.7.4--canary.357.11807</code></summary>
  <br />

  Try this version out locally by upgrading relevant packages to 0.7.4--canary.357.11807
</details>

### CODE REVIEW

**Comment by KetanReddy** [comment]
@sugarmanz just a heads up, it looks like the android circle image we're using is slated for deprecation in September. Do we have a plan on how to migrate to a newer one?

**Comment by sugarmanz** [comment]
> @sugarmanz just a heads up, it looks like the android circle image we're using is slated for deprecation in September. Do we have a plan on how to migrate to a newer one?

Yep, it's being updated as part of #324:
https://github.com/player-ui/player/pull/324/files#diff-78a8a19706dbd2a4425dd72bdab0502ed7a2cef16365ab7030a5a0588927bf47R33

**Comment by A1shK** [comment]
Created an issue #403 for this.

**Pull request closed without merging**
